---
galaxy_info:
  author: sbobopst
  description: Prometheus and Node Exporter monitoring stack
  license: MIT
  min_ansible_version: "2.20"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
