---
all:
  children:
    webservers:
      hosts:
        webserver01:
          ansible_host: 192.168.56.10

    dbservers:
      hosts:
        dbserver01:
          ansible_host: 192.168.56.11

    monitoring:
      hosts:
        monitor01:
          ansible_host: 192.168.56.12
