---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Ensure ansible user exists
  ansible.builtin.user:
    name: "{{ ansible_deploy_user }}"
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true

- name: Remove useless packages
  ansible.builtin.apt:
    autoremove: true
